### ISSUE TITLE
The drop downs in the FAQ section should reveal dropdown text

### ISSUE THREAD

**Issue by seanred360** [seanred360/bookmark-landing-page#4]
When the user clicks on 'What is a bookmark" a dropdown should reveal the answer to the question.

https://user-images.githubusercontent.com/41050673/194589094-12a785aa-3210-4e47-9bf7-32c3a1d54a29.mp4

**Comment by Ommanimesh2** [comment]
@seanred360 is this issue available ? I would like to work on this.

**Comment by seanred360** [comment]
> @seanred360 is this issue available ? I would like to work on this.

This issue is still available.

**Comment by Ommanimesh2** [comment]
Please assign this to me @seanred360

**Comment by Ommanimesh2** [comment]
I've opened a pull request resolving the same. Do check it out. @seanred360

**Comment by seanred360** [comment]
> I've opened a pull request resolving the same. Do check it out. @seanred360

Thanks for your help this is great!
